// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"todolist-api/app"
	"todolist-api/controller"
	"todolist-api/repository"
	"todolist-api/service"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from injector.go:

func InitializeServer() *gin.Engine {
	todolistRepository := repository.NewTodolistRepository()
	db := app.NewDB()
	todolistService := service.NewTodolistService(todolistRepository, db)
	todolistController := controller.NewTodolistController(todolistService)
	engine := app.NewRouter(todolistController)
	return engine
}
